POST http://localhost:3333/api/links
Content-Type: application/json

{
    "code": "instagram",
    "url": "http://instagram.com.br"
}

###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/instagram

###

GET http://localhost:3333/api/metrics